### PR TITLE
Integrate edit incident

### PR DESCRIPTION
**Pull request by v1b3m**
This PR integrates edit incident status and location into the UI.

To test this feature, please login(or sign up and then log in) in case you have no account yet:
-Register for an account at https://v1b3m.github.io/project_ireporter_api/UI/signup.html
-Then log in at https://v1b3m.github.io/project_ireporter_api/UI/signin.html

On logging in you, need to create an incident which will then be displayed on the home page, click on the title of the incident to get the incident details displayed to you in a pop up table, in the table header you'll see a link that says, `Edit this incident`, click on that and head on to change the data to the new updated data. This will redirect you to the incident page on completion and you can now check your incident to confirm that the data has been updated successfully.

@nicholus @Rhytah @JamesMudidi @sanya-kenneth @frankopkusianwar @AtamaZack @ManuelDominic @KabohaJeanMark @nadralia @reifred @llwasampijja @richien @Genza999 @3Nakajugo @e-ian @Manorlds-Eaglespark @PatrickMugayaJoel @bisonlou @kalsmic @mwinel

### CODE REVIEW

**Comment by richien** [comment]
Hi I was able to edit the the location and comment on an incident i had created. However, I was unable to select a location from the map when creating the incident.

**Comment by v1b3m** [comment]
> Hi I was able to edit the the location and comment on an incident i had created. However, I was unable to select a location from the map when creating the incident.
Thanks for the feedback, willis, I am working on that, I got a bag in the function supposed to fill that data into the form.

**Comment by v1b3m** [comment]
> > Hi I was able to edit the the location and comment on an incident i had created. However, I was unable to select a location from the map when creating the incident.
> > Thanks for the feedback, willis, I am working on that, I got a bag in the function supposed to fill that data into the form.

I believe I've fixed the issue, sir.
Thanks again

**Comment by kalsmic** [comment]
Well done, @v1b3m, Instead of the user moving the marker, it would be nice instead to update the position of the marker when the user clicks the new location on the map.

**Comment by v1b3m** [comment]
Ohh, that's a great insight, looks like it will improve the UI/UX. Thanks, Kalsmic. I will surely put this into consideration and also update you when I integrate the feature.

**Pull request merged**
